FROM golang:1.17 AS builder
WORKDIR /example
COPY . ./

RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 \
    go build -o example ./cmd/worker

FROM scratch
# COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /example/example .
ENTRYPOINT ["/example"]
